version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: callcentre-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - callcentre-network
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a $REDIS_PASSWORD ping | grep PONG"]
      interval: 30s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: callcentre-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:-postgresql://gen_user:j7X_S9mznbdGHc9P@5.129.247.54:5432/default_db}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-ff1ebf6b64951141ff4d0a4de1999b284e077eef9a4cc3c1d68e4cad222b4f7b}
      SSL_ENABLED: true
      SSL_CERT_DIR: /etc/ssl/certs/callcentre
      HTTPS_PORT: 443
      HTTP_PORT: 5000
      BACKEND_DOMAIN: apikc.lead-schem.ru
      FRONTEND_DOMAIN: callcentre.lead-schem.ru
      FRONTEND_URL: https://callcentre.lead-schem.ru
      MANGO_WEBHOOK_URL: https://apikc.lead-schem.ru/api/webhooks/mango
      # S3 настройки
      S3_ENDPOINT: https://s3.twcstorage.ru
      S3_BUCKET: f7eead03-crmfiles
      S3_REGION: ru-1
    volumes:
      - ./ssl:/etc/ssl/certs/callcentre:ro
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    secrets:
      - s3_access_key
      - s3_secret_key
    # Backend внутренний порт, без внешнего доступа
    expose:
      - "5000"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - callcentre-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: callcentre-frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://apikc.lead-schem.ru
      NEXT_PUBLIC_SOCKET_URL: wss://apikc.lead-schem.ru
      NEXT_PUBLIC_FRONTEND_DOMAIN: callcentre.lead-schem.ru
      NEXT_PUBLIC_BACKEND_DOMAIN: apikc.lead-schem.ru
    # Frontend внутренний порт, проксируется через nginx
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - callcentre-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: callcentre-nginx
    volumes:
      - ./config/nginx/callcentre-crm.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs/callcentre:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - callcentre-network

volumes:
  redis_data:
  backend_uploads:
  backend_logs:

networks:
  callcentre-network:
    driver: bridge

secrets:
  s3_access_key:
    external: true
  s3_secret_key:
    external: true
